name: check

on:
  push:
    branches: [main, staging, private]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux
          - aarch64-darwin
    runs-on: >-
      ${{ (matrix.system == 'x86_64-linux' && 'ubuntu-latest')
      || (matrix.system == 'aarch64-linux' && 'ubuntu-24.04-arm')
      || (matrix.system == 'aarch64-darwin' && 'macos-latest') }}

    steps:
      - uses: actions/checkout@v6
      - name: setup nix
        uses: ./.github/actions/setup-nix
        with:
          system: ${{ matrix.system }}
      - run: nix profile add .#attic-client
      - uses: ryanccn/attic-action@5635a15ef0c5462194ffbd05d1daeddc74625c3a
        with:
          endpoint: https://attic.defelo.de/
          cache: nixpkgs-review-gha
          # atticd-atticadm make-token --sub github --validity 1y --pull nixpkgs-review-gha --push nixpkgs-review-gha
          token: ${{ secrets.NRGHA_ATTIC_TOKEN }}
      - run: nix flake check -L --keep-going
